services:
  db:
    image: postgres:16
    container_name: odoo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mi_empresa
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d mi_empresa"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    build:
      context: .
      dockerfile: Dockerfile.odoo
    container_name: odoo19
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./config/odoo.docker.conf:/etc/odoo/odoo.conf:ro
      - ./modules:/mnt/extra-addons
    command: odoo -c /etc/odoo/odoo.conf

volumes:
  postgres_data:
  odoo_web_data:
