FROM odoo:19.0

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends python3-pip \
    && pip3 install --break-system-packages --no-cache-dir msal pandas pymssql reportlab Pillow python-dotenv requests sqlparse dropbox pyncclient nextcloud-api-wrapper boto3 paramiko \
    && rm -rf /var/lib/apt/lists/*

USER odoo
